export enum ErrorTypes {
    VALIDE = "VALIDE",
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
    EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND",
    WRONG_PASSWORD = "WRONG_PASSWORD",
    WRONG_EMAIL_TYPE = "WRONG_EMAIL_TYPE",
    PASSWORD_NOT_HAVE_UPPERCASE = "PASSWORD_NOT_HAVE_UPPERCASE",
    PASSWORD_NOT_HAVE_LOWERCASE = "PASSWORD_NOT_HAVE_LOWERCASE",
    PASSWORD_NOT_HAVE_NUMBER = "PASSWORD_NOT_HAVE_NUMBER",
    PASSWORD_NOT_HAVE_SPECIAL_SYMBOL = "PASSWORD_NOT_HAVE_SPECIAL_SYMBOL",
    PASSWORD_NOT_HAVE_MIN_LENGTH = "PASSWORD_NOT_HAVE_MIN_LENGTH",
    CONFIRM_PASSWORD_NOT_SAME = "CONFIRM_PASSWORD_NOT_SAME",
}