import { CvStatusType, EducationType, ExperienceType, ICv, SkillType } from "../types/dbTypes";

export const cvs: ICv[] = [
    {
        id: 1,
        name: 'Иван',
        surname: 'Иванов',
        cvName: 'Front-end developer',
        birthDate: new Date(1990, 1, 1),
        salary: 10000,
        telephonNumber: '+79999999999',
        skills: [SkillType.JavaScript, SkillType.TypeScript, SkillType.HTML, SkillType.CSS,],
        educations: [EducationType.BACHELOR, EducationType.MAGISTER],
        city: 'Москва',
        status: CvStatusType.ACTIVE,
        experience: ExperienceType.ONE_YEAR,
    },
    {
        id: 2,
        name: 'Петр',
        surname: 'Петров',
        cvName: 'Front-end developer',
        birthDate: new Date(1990, 1, 1),
        salary: 10000,
        telephonNumber: '+79999999999',
        skills: [SkillType.JavaScript, SkillType.TypeScript, SkillType.HTML, SkillType.CSS,],
        educations: [EducationType.BACHELOR, EducationType.MAGISTER],
        city: 'Москва',
        status: CvStatusType.ACTIVE,
        experience: ExperienceType.ONE_YEAR,
    },
    {
        id: 3,
        name: 'Сергей',
        surname: 'Сергеев',
        cvName: 'Back-end developer',
        birthDate: new Date(1990, 1, 1),
        salary: 10000,
        telephonNumber: '+79999999999',
        skills: [SkillType.JavaScript, SkillType.TypeScript, SkillType.HTML, SkillType.CSS, SkillType.Node, SkillType.Python],
        educations: [EducationType.BACHELOR, EducationType.MAGISTER],
        city: 'Москва',
        status: CvStatusType.ACTIVE,
        experience: ExperienceType.ONE_YEAR,
    },
    {
        id: 4,
        name: 'Алексей',
        surname: 'Алексеев',
        cvName: 'Back-end developer',
        birthDate: new Date(1990, 1, 1),
        salary: 10000,
        telephonNumber: '+79999999999',
        skills: [SkillType.JavaScript, SkillType.TypeScript, SkillType.HTML, SkillType.CSS, SkillType.Node, SkillType.Python],
        educations: [EducationType.BACHELOR, EducationType.MAGISTER],
        city: 'Москва',
        status: CvStatusType.ACTIVE,
        experience: ExperienceType.ONE_YEAR,
    },
    {
        id: 5,
        name: 'Алексей',
        surname: 'Алексеев',
        cvName: 'QA engineer',
        birthDate: new Date(1990, 1, 1),
        salary: 10000,
        telephonNumber: '+79999999999',
        skills: [SkillType.Linux, SkillType.Docker, SkillType.AWS, SkillType.Azure, SkillType.GCP],
        educations: [EducationType.BACHELOR, EducationType.MAGISTER],
        city: 'Москва',
        status: CvStatusType.ACTIVE,
        experience: ExperienceType.ONE_YEAR,
    },
    {
        id: 6,
        name: 'Алексей',
        surname: 'Алексеев',
        cvName: 'QA engineer',
        birthDate: new Date(1990, 1, 1),
        salary: 10000,
        telephonNumber: '+79999999999',
        skills: [SkillType.Linux, SkillType.Docker, SkillType.AWS, SkillType.Azure, SkillType.GCP],
        educations: [EducationType.BACHELOR, EducationType.MAGISTER],
        city: 'Москва',
        status: CvStatusType.ACTIVE,
        experience: ExperienceType.ONE_YEAR,
    }
]